version: '3.8'
services:
  eureka-server:
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - sistema-educativo-network

  config-server:
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    networks:
      - sistema-educativo-network

  usuarios-servicio:
    build:
      context: ./usuarios-servicio
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - sistema-educativo-network
    depends_on:
      - eureka-server
      - config-server

  asignaturas-servicio:
    build:
      context: ./asignaturas-servicio
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - sistema-educativo-network
    depends_on:
      - eureka-server
      - config-server

  matriculas-servicio:
    build:
      context: ./matriculas-servicio
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - sistema-educativo-network
    depends_on:
      - eureka-server
      - config-server

networks:
  sistema-educativo-network:
    driver: bridge